# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8NnanlWvJySr3NldtshNlQ8z-zVS6GW
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import json

##Data modeliing

!git clone https://github.com/CHILab1/MedPix-2.0.git
# %cd MedPix-2.0
# %cd splitted_dataset/

#Create a data file
# Read the JSON Lines file line by line
data1 = []
with open('data_train_1.jsonl', 'r') as f:
    for line in f:
        data1.append(pd.json_normalize(json.loads(line)))


# Concatenate the list of dataframes into a single dataframe
df1 = pd.concat(data1, ignore_index=True)

l#en(df1['U_id'].unique())

# Read the JSON Lines file line by line
data2 = []
with open('descriptions_train_1.jsonl', 'r') as f:
    for line in f:
        data2.append(pd.json_normalize(json.loads(line)))

# Concatenate the list of dataframes into a single dataframe
df2 = pd.concat(data2, ignore_index=True)

#print(df2)

#len(df2['U_id'].unique())

train_data = pd.merge(df1, df2, on='U_id')
#train_data.columns

clean_data = train_data.loc[:, train_data.isna().any() == False]
clean_data['image_path'] = clean_data['image'].apply(lambda x: '/content/drive/MyDrive/Falcon_Healthcare_agent/MedPix-2.0/images/' + x + '.png')
clean_data['image_path']

#Sampling

image_list = list(clean_data['image_path'][0:10])

sample_10 = clean_data[0:10]

sample_10.to_csv('sample_10_final.csv')

print(sample_10.columns)

sample_10 = sample_10[['U_id','Case.Case Diagnosis', 'Case.Title','Topic.Category', 'Topic.Disease Discussion',
       'Topic.Title', 'Type', 'Location', 'Location Category',
       'Description.ACR Codes', 'Description.Age', 'Description.Caption',
       'Description.Modality', 'Description.Sex']]