# -*- coding: utf-8 -*-
"""helper_functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EorDSy_mc1wGh77hsZvTId0xq1mnb31h
"""

import torch
from ImageBind import ImageBind_model_load
from imagebind.models import imagebind_model
from imagebind.models.imagebind_model import ModalityType
from imagebind import data
import pandas as pd


model = ImageBind_model_load()

# Helper function to create embeddings
def get_embedding_vector(inputs, device):
    with torch.no_grad():
        embedding = model(inputs)
        for key, value in embedding.items():
            vec = value.reshape(-1)
            vec = vec.numpy()
            return vec

# Helper function to create a query vector from a natural language query
def QuerytoEmbedding(text, device):
    text = [text]
    inputs = {
         ModalityType.TEXT: data.load_and_transform_text(text, device)
        }
    vec = get_embedding_vector(inputs,device)
    return(vec)



def build_context(relevant_docs):
    context = ""
    relevant_images = []
    for d in relevant_docs['matches']:
        metadata = d.metadata
        context += f"[{metadata['type']}]" + metadata['Text']
        relevant_images.append(metadata['Image'])
    return context