# -*- coding: utf-8 -*-
"""ImageBind_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11tw2mNMzKX1adwY4k6Qu9n6D03ok17X_
"""

import torch
from lavis.models import imagebind_model
import os
!git clone https://github.com/facebookresearch/ImageBind.git
### Move to the ImageBind directory
os.chdir('./ImageBind')

#Device and mpodel
device = "cuda:0" if torch.cuda.is_available() else "cpu"
# Instantiate model
def ImageBind_model_lod()
  return imagebind_model.imagebind_huge(pretrained=True)


#model.eval()
#model.to(device)