# -*- coding: utf-8 -*-
"""llm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UuAfgaPVH6F4vgSwiIDed9n9SVKa5Pv1
"""

#LLM
import os
from dotenv import load_dotenv
import openai
from openai import OpenAI
from langchain.chat_models import ChatOpenAI
from langchain.schema import (
    AIMessage,
    HumanMessage,
    SystemMessage
)
load_dotenv()

#openai.api_key = os.getenv("OPENAI_API_KEY")
def open_ai():
  return OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


def llm():
  return ChatOpenAI(
    model="gpt-3.5-turbo",
    api_key=os.getenv("OPENAI_API_KEY"),
    streaming=True,)

def open_ai_a171():
  return openai.OpenAI(
    api_key=AI71_API_KEY,
    base_url=AI71_BASE_URL,
)