# -*- coding: utf-8 -*-
"""vector_db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jrNpC1kRVchcVye9DxAKSit74ILflx9J
"""

#LLM
import os
from dotenv import load_dotenv
from langchain_pinecone import PineconeVectorStore
from pinecone import Pinecone, ServerlessSpec

load_dotenv()

#openai.api_key = os.getenv("OPENAI_API_KEY")
def vector_db():
  return Pinecone(api_key=os.getenv("PINECONE_API_KEY")))